# Generated by Django 4.2.1 on 2023-05-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='position',
            new_name='position_ghost_x',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='score',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='match',
            name='host_has_ball',
        ),
        migrations.RemoveField(
            model_name='match',
            name='velocity_x',
        ),
        migrations.RemoveField(
            model_name='match',
            name='velocity_y',
        ),
        migrations.AddField(
            model_name='match',
            name='number_of_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='position_ghost_z',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
    ]
